# Generated by Django 2.2.2 on 2019-07-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
